name: CI Build
on:
    push:
        branches:
            - "main"
            - "release/*"
    pull_request:
        # none
jobs:
    Build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: "true"
            - name: Setup .NET
              uses: actions/setup-dotnet@v2
            - name: Restore
              run: dotnet restore
            - name: Build
              run: dotnet build -c Release --no-restore
            - name: Test
              run: dotnet test --no-build
            - name: Pack
              run: dotnet pack -c Release -o ./packages-out/ --version-suffix build${{ github.run_number }}.0
            - name: Push to GitHub Packages
              if: ${{ github.repository == 'dotnet/Silk.NET' && github.event_name != 'pull_request' }}
              run: dotnet nuget push ./packages-out/*.nupkg --force-english-output -s https://nuget.pkg.github.com/dotnet/index.json -k ${{ secrets.GITHUB_TOKEN }}
            - uses: actions/upload-artifact@v3
              with:
                  name: packages
                  path: ./packages-out/
