name: CD Build

on:
  push:
    tags:
      - '*'

jobs:
  Publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100-preview.8.20417.9
    - name: Pack
      run: ./build.cmd pack
    - name: Test
      run: ./build.cmd test
    - name: Setup NuGet
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: '5.x'
    - name: Push to NuGet
      run: nuget push "build/output_packages/Silk.NET.*.nupkg" -SkipDuplicate -Source https://api.nuget.org/v3/index.json -ApiKey ${{ secrets.NUGET_TOKEN }}
