name: Website Build
on:
    push:
        branches:
            - "develop/3.0"
jobs:
    Build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  submodules: "true"
            - name: Setup .NET 6.0
              uses: actions/setup-dotnet@v1
              with:
                  dotnet-version: 6.0.201
            - name: Run Statiq
              run: dotnet run -c Release --project src/Website/Silk.NET.Statiq/Silk.NET.Statiq.csproj -- -l debug --nocache
            - name: Install wrangler
              run: npm install -g wrangler@beta
            - name: Install Deps of CF worker
              run: npm i
              working-directory: ./website/cf-worker/
            - name: Publish
              run: wrangler publish
