name: SDL2
on:
  push:
    branches-ignore:
      - "ci/*"
      - "develop/*"
      - "main"
    paths:
      - "build/submodules/SDL"
      - "build/nuke/Build.Native.cs"
      - ".github/workflows/sdl2.yml"
jobs:
  Build:
    strategy:
      fail-fast: false
      matrix:
        env:
          - os: ubuntu-latest
            name: Linux
            nuke_invoke: ./build.sh
            # extras: |
              # sudo apt-get update
              # sudo apt-get install -y gcc-multilib
          # - os: windows-latest
          #   name: Windows
          #   nuke_invoke: ./build.cmd
          #   extras: ""
          # - os: macos-latest
          #   name: Darwin
          #   nuke_invoke: ./build.sh
          #   extras: ""
    name: ${{ matrix.env.name }} Build
    runs-on: ${{ matrix.env.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PUSHABLE_GITHUB_TOKEN }}

      - name: Checkout submodules, configure git
        run: |
          git -c submodule.third_party/git-hooks.update=none submodule update --init --recursive build/submodules/SDL
          git config --local user.email "9011267+dotnet-bot@users.noreply.github.com"
          git config --local user.name "The Silk.NET Automaton"

      - name: Extra prerequisites
        run: |
          echo running extras
          ${{ matrix.env.extras }}

      - name: Build SDL2
        if: runner.os == 'Linux'
        uses: Beyley/run-as-1804@239b211a2ca687388b6251d6dab22cb90ac0391d
        with:
          command: |
            apt update
            apt install -y curl wget build-essential git make autoconf automake libtool pkg-config cmake ninja-build gnome-desktop-testing libasound2-dev libpulse-dev libaudio-dev libjack-dev libsndio-dev libsamplerate0-dev libx11-dev libxext-dev libxrandr-dev libxcursor-dev libxfixes-dev libxi-dev libxss-dev libwayland-dev libxkbcommon-dev libdrm-dev libgbm-dev libgl1-mesa-dev libgles2-mesa-dev libegl1-mesa-dev libdbus-1-dev libibus-1.0-dev libudev-dev fcitx-libs-dev

            wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh
            chmod +x ./dotnet-install.sh
            ./dotnet-install.sh --version 6.0.0
            ./dotnet-install.sh --version 7.0.2

            ${{ matrix.env.nuke_invoke }} SDL2
        env:
          PUSHABLE_GITHUB_TOKEN: ${{ secrets.PUSHABLE_GITHUB_TOKEN }}

      - name: Build SDL2
        if: runner.os != 'Linux'
        run: ${{ matrix.env.nuke_invoke }} SDL2
        env:
          PUSHABLE_GITHUB_TOKEN: ${{ secrets.PUSHABLE_GITHUB_TOKEN }}
      

