name: SwiftShader
on:
  push:
    paths:
      - build/submodules/SwiftShader
      - .github/workflows/SwiftShader.yml  # temporary for dev
jobs:
  Build:
    strategy: 
      matrix:
        env:
          - os: ubuntu-latest
            name: Linux
            nuke_invoke: ./build.sh
          - os: windows-latest
            name: Windows
            nuke_invoke: ./build.cmd
          - os: macos-latest
            name: Darwin
            nuke_invoke: ./build.sh
    name: ${{ matrix.env.name }} Build
    runs-on: ${{ matrix.env.os }}
    steps:
      - uses: actions/checkout@v1
      - run: |
          git -c submodule.third_party/git-hooks.update=none submodule update --init --recursive
          git config --local user.email "9011267+dotnet-bot@users.noreply.github.com"
          git config --local user.name "The Silk.NET Automaton" 
      - name: Cache .tmp, ~/.nuget/packages
        uses: actions/cache@v2
        with:
          path: |
            .tmp
            ~/.nuget/packages
          key: ${{ runner.os }}-${{ hashFiles('**/global.json', '**/*.csproj') }}
      - name: Build SwiftShader
        run: ${{ matrix.env.nuke_invoke }} SwiftShader
        env:
          PUSHABLE_GITHUB_TOKEN: ${{ secrets.PUSHABLE_GITHUB_TOKEN }}
