name: SwiftShader
on:
  push:
    paths:
      - build/submodules/SwiftShader
      - .github/workflows/SwiftShader.yml  # temporary for dev
jobs:
  Build:
    strategy: 
      matrix:
        env:
          - os: ubuntu-latest
            name: Linux
            nuke_invoke: ./build.sh
          - os: windows-latest
            name: Windows
            nuke_invoke: ./build.cmd
          - os: macos-latest
            name: Darwin
            nuke_invoke: ./build.sh
    name: ${{ matrix.name }} Build
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - name: Cache .nuke/temp, ~/.nuget/packages
        uses: actions/cache@v2
        with:
          path: |
            .nuke/temp
            ~/.nuget/packages
          key: ${{ runner.os }}-${{ hashFiles('**/global.json', '**/*.csproj') }}
      - name: Build SwiftShader
        run: ${{ matrix.nuke_invoke }} SwiftShader
        env:
          PUSHABLE_GITHUB_TOKEN: ${{ secrets.PUSHABLE_GITHUB_TOKEN }}